services:
  local-db:
    container_name: local-db
    image: postgres
    environment:
      - POSTGRES_PASSWORD=local
      - POSTGRES_USER=local
      - POSTGRES_DB=local
      - PGPORT=5432
    ports:
      - "5432:5432"
    volumes:
      - ./databases/core-db:/var/lib/postgresql/data

  test-db:
    container_name: test-db
    image: postgres
    environment:
      - POSTGRES_PASSWORD=local
      - POSTGRES_USER=local
      - POSTGRES_DB=local
      - PGPORT=6543
    ports:
      - "6543:6543"
