name: budget-app
services:
  budget-web-client:
    container_name: budget-web-client
    build:
      dockerfile: ./Dockerfile.prd
      args:
        NEXT_PUBLIC_BASE_URL: http://localhost:3000
    expose:
      - 3000
    env_file:
      - ./.env.production
    networks:
        - budgetapp-net
  prd-db:
    container_name: prd-db
    image: postgres
    environment:
      - POSTGRES_PASSWORD=prd
      - POSTGRES_USER=prd
      - POSTGRES_DB=prd
      - PGPORT=5432
    ports:
      - "5432:5432"
    volumes:
      - ./databases/prd-core-db:/var/lib/postgresql/data
    networks:
        - budgetapp-net
networks:
  budgetapp-net:
    name: budgetapp-net
    driver: bridge
