FROM node:20-alpine
WORKDIR /app
COPY . .
RUN apk add --no-cache openssl
RUN yarn global add typescript
RUN yarn install

# only for NEXT_PUBLIC_ values 
# https://stackoverflow.com/questions/76124346/how-can-i-pass-an-env-variable-to-next-js-app-running-inside-a-docker-container
ARG NEXT_PUBLIC_BASE_URL
ENV NEXT_PUBLIC_BASE_URL=$NEXT_PUBLIC_BASE_URL

RUN yarn build 
CMD ["yarn", "start"]