name: Build Test & Unit/Int. Tests
on:
  pull_request:
    branches: [main, master]
jobs:
  Test:
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: local
          POSTGRES_USER: local
          POSTGRES_DB: local
          PGPORT: 6543
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 6543:6543
    runs-on: ubuntu-latest
    env:
      DATABASE_URL: postgresql://local:local@localhost:6543/local

      AUTH0_ISSUER_BASE_URL: ${{ secrets.AUTH0_ISSUER_BASE_URL }}

      AUTH0_MANAGEMENT_API_CLIENT_ID: ${{ secrets.AUTH0_MANAGEMENT_API_CLIENT_ID }}
      AUTH0_MANAGEMENT_API_CLIENT_SECRET: ${{ secrets.AUTH0_MANAGEMENT_API_CLIENT_SECRET }}

      TZ: UTC
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 20
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Install jq
        uses: dcarbone/install-jq-action@v2.1.0
      - name: Build + Generate API Client
        run: yarn build
      - name: Unit Test
        run: yarn test:unit --run
      - name: Setup DB Schemas
        run: yarn prisma migrate deploy
      - name: Seed DB
        run: |
          echo "Grabbing Auth0 Management API token"

          response=$(curl --request POST \
          --url $AUTH0_ISSUER_BASE_URL/oauth/token \
          --header 'content-type: application/json' \
          --data "{\"client_id\":\"$AUTH0_MANAGEMENT_API_CLIENT_ID\",\"client_secret\":\"$AUTH0_MANAGEMENT_API_CLIENT_SECRET\",\"audience\":\"https://dev-uw0vq8v32kjv4k1a.us.auth0.com/api/v2/\",\"grant_type\":\"client_credentials\"}")

          token=$(echo $response | jq -r '.access_token')

          export AUTH0_TMP_API_TOKEN=$token

          echo "Migrating users from auth0 db to local db"
          npx tsx ./prisma/seeds/migrate-users.ts

          echo "Migrating other static data to db"
          chmod +x ./scripts/migrate.sh
          ./scripts/migrate.sh
      - name: Integration Test
        run: vitest -c vitest.integration.config.ts --run
